# Generated by Django 3.0.4 on 2020-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=50)),
                ('vote_count', models.PositiveSmallIntegerField(default=0)),
                ('date_create', models.DateField()),
                ('graph_code_js', models.TextField()),
                ('replicate_data_query', models.TextField()),
                ('update_data_query', models.TextField()),
            ],
        ),
    ]
