# Generated by Django 3.0.4 on 2020-03-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_graphic_crud', '0002_auto_20200326_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='replicate_data_query',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='update_data_query',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='vote_count',
        ),
    ]
